// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: abdalgorithm.proto

#include "abdalgorithm.pb.h"
#include "abdalgorithm.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace abd {

static const char* ClientRead_method_names[] = {
  "/abd.ClientRead/SendRead",
};

std::unique_ptr< ClientRead::Stub> ClientRead::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClientRead::Stub> stub(new ClientRead::Stub(channel, options));
  return stub;
}

ClientRead::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendRead_(ClientRead_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClientRead::Stub::SendRead(::grpc::ClientContext* context, const ::abd::read_request& request, ::abd::read_reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::read_request, ::abd::read_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendRead_, context, request, response);
}

void ClientRead::Stub::async::SendRead(::grpc::ClientContext* context, const ::abd::read_request* request, ::abd::read_reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::read_request, ::abd::read_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRead_, context, request, response, std::move(f));
}

void ClientRead::Stub::async::SendRead(::grpc::ClientContext* context, const ::abd::read_request* request, ::abd::read_reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRead_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::read_reply>* ClientRead::Stub::PrepareAsyncSendReadRaw(::grpc::ClientContext* context, const ::abd::read_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::read_reply, ::abd::read_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendRead_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::read_reply>* ClientRead::Stub::AsyncSendReadRaw(::grpc::ClientContext* context, const ::abd::read_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendReadRaw(context, request, cq);
  result->StartCall();
  return result;
}

ClientRead::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientRead_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientRead::Service, ::abd::read_request, ::abd::read_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientRead::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::read_request* req,
             ::abd::read_reply* resp) {
               return service->SendRead(ctx, req, resp);
             }, this)));
}

ClientRead::Service::~Service() {
}

::grpc::Status ClientRead::Service::SendRead(::grpc::ServerContext* context, const ::abd::read_request* request, ::abd::read_reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ClientReadWriteback_method_names[] = {
  "/abd.ClientReadWriteback/SendReadWriteback",
};

std::unique_ptr< ClientReadWriteback::Stub> ClientReadWriteback::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClientReadWriteback::Stub> stub(new ClientReadWriteback::Stub(channel, options));
  return stub;
}

ClientReadWriteback::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendReadWriteback_(ClientReadWriteback_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClientReadWriteback::Stub::SendReadWriteback(::grpc::ClientContext* context, const ::abd::read_writeback& request, ::abd::read_writeback_reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::read_writeback, ::abd::read_writeback_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendReadWriteback_, context, request, response);
}

void ClientReadWriteback::Stub::async::SendReadWriteback(::grpc::ClientContext* context, const ::abd::read_writeback* request, ::abd::read_writeback_reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::read_writeback, ::abd::read_writeback_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendReadWriteback_, context, request, response, std::move(f));
}

void ClientReadWriteback::Stub::async::SendReadWriteback(::grpc::ClientContext* context, const ::abd::read_writeback* request, ::abd::read_writeback_reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendReadWriteback_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::read_writeback_reply>* ClientReadWriteback::Stub::PrepareAsyncSendReadWritebackRaw(::grpc::ClientContext* context, const ::abd::read_writeback& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::read_writeback_reply, ::abd::read_writeback, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendReadWriteback_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::read_writeback_reply>* ClientReadWriteback::Stub::AsyncSendReadWritebackRaw(::grpc::ClientContext* context, const ::abd::read_writeback& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendReadWritebackRaw(context, request, cq);
  result->StartCall();
  return result;
}

ClientReadWriteback::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientReadWriteback_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientReadWriteback::Service, ::abd::read_writeback, ::abd::read_writeback_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientReadWriteback::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::read_writeback* req,
             ::abd::read_writeback_reply* resp) {
               return service->SendReadWriteback(ctx, req, resp);
             }, this)));
}

ClientReadWriteback::Service::~Service() {
}

::grpc::Status ClientReadWriteback::Service::SendReadWriteback(::grpc::ServerContext* context, const ::abd::read_writeback* request, ::abd::read_writeback_reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ClientWrite_method_names[] = {
  "/abd.ClientWrite/SendWrite",
};

std::unique_ptr< ClientWrite::Stub> ClientWrite::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClientWrite::Stub> stub(new ClientWrite::Stub(channel, options));
  return stub;
}

ClientWrite::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendWrite_(ClientWrite_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClientWrite::Stub::SendWrite(::grpc::ClientContext* context, const ::abd::write_request& request, ::abd::write_reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::write_request, ::abd::write_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendWrite_, context, request, response);
}

void ClientWrite::Stub::async::SendWrite(::grpc::ClientContext* context, const ::abd::write_request* request, ::abd::write_reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::write_request, ::abd::write_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendWrite_, context, request, response, std::move(f));
}

void ClientWrite::Stub::async::SendWrite(::grpc::ClientContext* context, const ::abd::write_request* request, ::abd::write_reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendWrite_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::write_reply>* ClientWrite::Stub::PrepareAsyncSendWriteRaw(::grpc::ClientContext* context, const ::abd::write_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::write_reply, ::abd::write_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendWrite_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::write_reply>* ClientWrite::Stub::AsyncSendWriteRaw(::grpc::ClientContext* context, const ::abd::write_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendWriteRaw(context, request, cq);
  result->StartCall();
  return result;
}

ClientWrite::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientWrite_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientWrite::Service, ::abd::write_request, ::abd::write_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientWrite::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::write_request* req,
             ::abd::write_reply* resp) {
               return service->SendWrite(ctx, req, resp);
             }, this)));
}

ClientWrite::Service::~Service() {
}

::grpc::Status ClientWrite::Service::SendWrite(::grpc::ServerContext* context, const ::abd::write_request* request, ::abd::write_reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ClientWriteback_method_names[] = {
  "/abd.ClientWriteback/SendWriteback",
};

std::unique_ptr< ClientWriteback::Stub> ClientWriteback::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClientWriteback::Stub> stub(new ClientWriteback::Stub(channel, options));
  return stub;
}

ClientWriteback::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendWriteback_(ClientWriteback_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClientWriteback::Stub::SendWriteback(::grpc::ClientContext* context, const ::abd::writeback_request& request, ::abd::writeback_reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::writeback_request, ::abd::writeback_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendWriteback_, context, request, response);
}

void ClientWriteback::Stub::async::SendWriteback(::grpc::ClientContext* context, const ::abd::writeback_request* request, ::abd::writeback_reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::writeback_request, ::abd::writeback_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendWriteback_, context, request, response, std::move(f));
}

void ClientWriteback::Stub::async::SendWriteback(::grpc::ClientContext* context, const ::abd::writeback_request* request, ::abd::writeback_reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendWriteback_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::writeback_reply>* ClientWriteback::Stub::PrepareAsyncSendWritebackRaw(::grpc::ClientContext* context, const ::abd::writeback_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::writeback_reply, ::abd::writeback_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendWriteback_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::writeback_reply>* ClientWriteback::Stub::AsyncSendWritebackRaw(::grpc::ClientContext* context, const ::abd::writeback_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendWritebackRaw(context, request, cq);
  result->StartCall();
  return result;
}

ClientWriteback::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientWriteback_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientWriteback::Service, ::abd::writeback_request, ::abd::writeback_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientWriteback::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::writeback_request* req,
             ::abd::writeback_reply* resp) {
               return service->SendWriteback(ctx, req, resp);
             }, this)));
}

ClientWriteback::Service::~Service() {
}

::grpc::Status ClientWriteback::Service::SendWriteback(::grpc::ServerContext* context, const ::abd::writeback_request* request, ::abd::writeback_reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* GetLock_method_names[] = {
  "/abd.GetLock/AcquireLock",
};

std::unique_ptr< GetLock::Stub> GetLock::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GetLock::Stub> stub(new GetLock::Stub(channel, options));
  return stub;
}

GetLock::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AcquireLock_(GetLock_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GetLock::Stub::AcquireLock(::grpc::ClientContext* context, const ::abd::lock_request& request, ::abd::lock_reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::abd::lock_request, ::abd::lock_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AcquireLock_, context, request, response);
}

void GetLock::Stub::async::AcquireLock(::grpc::ClientContext* context, const ::abd::lock_request* request, ::abd::lock_reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::abd::lock_request, ::abd::lock_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcquireLock_, context, request, response, std::move(f));
}

void GetLock::Stub::async::AcquireLock(::grpc::ClientContext* context, const ::abd::lock_request* request, ::abd::lock_reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcquireLock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::abd::lock_reply>* GetLock::Stub::PrepareAsyncAcquireLockRaw(::grpc::ClientContext* context, const ::abd::lock_request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::abd::lock_reply, ::abd::lock_request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AcquireLock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::abd::lock_reply>* GetLock::Stub::AsyncAcquireLockRaw(::grpc::ClientContext* context, const ::abd::lock_request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAcquireLockRaw(context, request, cq);
  result->StartCall();
  return result;
}

GetLock::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GetLock_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GetLock::Service, ::abd::lock_request, ::abd::lock_reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GetLock::Service* service,
             ::grpc::ServerContext* ctx,
             const ::abd::lock_request* req,
             ::abd::lock_reply* resp) {
               return service->AcquireLock(ctx, req, resp);
             }, this)));
}

GetLock::Service::~Service() {
}

::grpc::Status GetLock::Service::AcquireLock(::grpc::ServerContext* context, const ::abd::lock_request* request, ::abd::lock_reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace abd
#include <grpcpp/ports_undef.inc>

